---
- hosts: localhost
  remote_user: root
  become: yes
  become_user: root
  tasks:
  - group: name=devops state=present
  - name: create devops user with admin privileges
    user: name=devops comment="Dev user" uid=2001 group=devops
    

    
